version: "3"

services:
  frontend:
    command: "sh -c 'npm i && npm run dev'"
    environment:
      - NEXT_PUBLIC_APP_ENV=local
  api:
    command: "sh -c 'npm i && npm run dev'"

  auth:
    command: "sh -c 'npm i && npm run dev'"

  nginx:
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/nginx.conf